# Generated by Django 4.2.12 on 2024-09-19 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "name",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("description", models.TextField()),
                ("privacy", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=32)),
                ("email", models.CharField(max_length=64)),
                ("password", models.CharField(max_length=64)),
                ("profile_picture", models.URLField(null=True)),
                ("bio", models.TextField(null=True)),
                ("pronouns", models.CharField(max_length=32, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("online_status", models.BooleanField(default=False)),
                ("real_name", models.CharField(max_length=128, null=True)),
                ("privacy", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.IntegerField(primary_key=True, serialize=False)),
                ("text", models.TextField(null=True)),
                ("sensitive", models.BooleanField(default=False)),
                ("location_tag", models.TextField(null=True)),
                (
                    "forum_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nexus_app.forum",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nexus_app.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="forum",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nexus_app.user"
            ),
        ),
    ]
