# Generated by Django 4.2.12 on 2024-09-20 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nexus_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.IntegerField(primary_key=True, serialize=False)),
                ("creation_date", models.DateTimeField(auto_now=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nexus_app.post"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nexus_app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("session_id", models.UUIDField(primary_key=True, serialize=False)),
                ("expiration", models.DateTimeField()),
                ("activity", models.TimeField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nexus_app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("report_id", models.IntegerField(primary_key=True, serialize=False)),
                ("reason", models.TextField()),
                ("reported_at", models.DateTimeField()),
                (
                    "comment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nexus_app.comment",
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nexus_app.post",
                    ),
                ),
                (
                    "report_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_sender",
                        to="nexus_app.user",
                    ),
                ),
                (
                    "reported_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_user",
                        to="nexus_app.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_type", models.CharField(max_length=8)),
                ("url", models.URLField()),
                ("index", models.IntegerField(default=0)),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nexus_app.post"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                ("message_id", models.IntegerField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("sent", models.DateTimeField()),
                (
                    "from_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sending_user",
                        to="nexus_app.user",
                    ),
                ),
                (
                    "to_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiving_user",
                        to="nexus_app.user",
                    ),
                ),
            ],
        ),
    ]
