# Generated by Django 4.2.12 on 2024-09-26 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nexus_app", "0007_alter_comment_comment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nexus_app.comment",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="comment_setting",
            field=models.CharField(
                choices=[("ALL", "All"), ("FOLLOWING", "Following"), ("NONE", "None")],
                default="ALL",
                max_length=9,
            ),
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like", models.BooleanField(default=True)),
                (
                    "comment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nexus_app.comment",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nexus_app.user",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="commentlike",
            constraint=models.UniqueConstraint(
                fields=("comment_id", "user_id"), name="comment_like_unq_constraint"
            ),
        ),
    ]
