# Generated by Django 4.2.12 on 2024-10-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexus_app", "0009_post_creation_date_post_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
