# Generated by Django 4.2.12 on 2024-10-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexus_app", "0011_userprofile_remove_session_user_id_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="commentlike",
            constraint=models.UniqueConstraint(
                fields=("comment", "user"), name="comment_like_unq_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("user", "following"), name="follow_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="forumfollow",
            constraint=models.UniqueConstraint(
                fields=("user", "forum"), name="forum_follow_unq_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="forummoderator",
            constraint=models.UniqueConstraint(
                fields=("forum", "user"), name="forum_moderator_unq_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="postbookmark",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="post_bookmark_unq_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="postlike",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="post_like_unq_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="postusertag",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="post_user_tag_unq_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="userblock",
            constraint=models.UniqueConstraint(
                fields=("user", "blocked"), name="user_block_constraint"
            ),
        ),
    ]