# Generated by Django 4.2.12 on 2024-10-10 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nexus_app", "0015_messageconversation_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageconversation",
            name="last_message",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nexus_app.message",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="nexus_app.messageconversation",
            ),
        ),
        migrations.AlterField(
            model_name="messageconversationmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member",
                to="nexus_app.userprofile",
            ),
        ),
    ]
