# Generated by Django 4.2.12 on 2024-10-21 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("nexus_app", "0018_userprofile_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="postbookmark",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postlike",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="followers",
            field=models.ManyToManyField(
                related_name="following_users",
                through="nexus_app.Follow",
                to="nexus_app.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="following",
            field=models.ManyToManyField(
                related_name="followed_users",
                through="nexus_app.Follow",
                to="nexus_app.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="likes",
            field=models.ManyToManyField(
                through="nexus_app.PostLike", to="nexus_app.post"
            ),
        ),
    ]
