# Generated by Django 4.2.12 on 2024-09-20 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_site", "0003_usermutedword_userblock_postusertag_postlike_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="test_site.user",
                    ),
                ),
                ("language", models.CharField(max_length=2)),
                (
                    "sensitive_content_behavior",
                    models.CharField(
                        choices=[("SHOW", "Show"), ("BLUR", "Blur"), ("HIDE", "Hide")],
                        default="BLUR",
                        max_length=4,
                    ),
                ),
            ],
        ),
    ]
