# Generated by Django 4.2.12 on 2024-09-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_site", "0004_usersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="pronouns",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="real_name",
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
