# Generated by Django 4.2.12 on 2024-09-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_site", "0005_alter_user_bio_alter_user_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
