# Generated by Django 4.2.12 on 2024-10-09 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_site", "0014_message_messageconversation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageconversation",
            name="name",
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="messageconversation",
            name="creator",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator",
                to="test_site.userprofile",
            ),
        ),
    ]
