# Generated by Django 4.2.12 on 2024-10-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_site", "0017_rename_real_name_userprofile_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="banner",
            field=models.URLField(default=None, null=True),
        ),
    ]
